/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ExpressionNode,
  ProgramNode,
  StatementNode,
} from './types';

// ==========================================
// Python 3 Code Generator
// ==========================================
export class PythonGenerator {
  private indentLevel = 0;

  public generate(ast: ProgramNode): string {
    this.indentLevel = 0;
    const lines: string[] = [
      '#!/usr/bin/env python3',
      '# -*- coding: utf-8 -*-',
      '"""',
      '  Generated by SylhetiLang Compiler',
      '  Bangla & Sylheti High-Performance Pipeline',
      '"""',
      'import math',
      'import sys',
      '',
      '# Sylheti Standard Library Runtime Mappings',
      'def কও(*args):',
      '    print(*args)',
      '',
      'def লও(prompt=""):',
      '    if prompt: print(prompt, end="")',
      '    return input()',
      '',
      'def দৈর্ঘ্য(obj):',
      '    return len(obj)',
      '',
      'def বর্গমূল(val):',
      '    return math.sqrt(val)',
      '',
      'def পরমমান(val):',
      '    return abs(val)',
      '',
      '# --- Program Start ---',
      '',
    ];

    for (const stmt of ast.body) {
      lines.push(this.generateStatement(stmt));
    }

    return lines.join('\n');
  }

  private indent(): string {
    return '    '.repeat(this.indentLevel);
  }

  private generateStatement(stmt: StatementNode): string {
    switch (stmt.type) {
      case 'VarDecl': {
        const init = stmt.init ? this.generateExpression(stmt.init) : 'None';
        return `${this.indent()}${stmt.identifier} = ${init}`;
      }

      case 'Assignment': {
        const val = this.generateExpression(stmt.value);
        if (stmt.index) {
          const idx = this.generateExpression(stmt.index);
          return `${this.indent()}${stmt.identifier}[${idx}] ${stmt.operator} ${val}`;
        }
        return `${this.indent()}${stmt.identifier} ${stmt.operator} ${val}`;
      }

      case 'IfStmt': {
        const cond = this.generateExpression(stmt.condition);
        let res = `${this.indent()}if ${cond}:\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.consequent);
        this.indentLevel--;

        if (stmt.alternate) {
          if (stmt.alternate.type === 'IfStmt') {
            res += `\n${this.indent()}el${this.generateStatement(stmt.alternate).trimStart()}`;
          } else {
            res += `\n${this.indent()}else:\n`;
            this.indentLevel++;
            res += this.generateStatement(stmt.alternate);
            this.indentLevel--;
          }
        }
        return res;
      }

      case 'WhileStmt': {
        const cond = this.generateExpression(stmt.condition);
        let res = `${this.indent()}while ${cond}:\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.body);
        this.indentLevel--;
        return res;
      }

      case 'ForStmt': {
        let res = '';
        if (stmt.init) {
          res += this.generateStatement(stmt.init) + '\n';
        }
        const cond = stmt.condition ? this.generateExpression(stmt.condition) : 'True';
        res += `${this.indent()}while ${cond}:\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.body);
        if (stmt.update) {
          if ('type' in stmt.update && typeof stmt.update.type === 'string') {
            if (stmt.update.type === 'Assignment' || stmt.update.type === 'ExpressionStmt') {
              res += '\n' + this.generateStatement(stmt.update as StatementNode);
            } else {
              res += '\n' + this.indent() + this.generateExpression(stmt.update as ExpressionNode);
            }
          }
        }
        this.indentLevel--;
        return res;
      }

      case 'BlockStmt': {
        if (stmt.statements.length === 0) {
          return `${this.indent()}pass`;
        }
        return stmt.statements.map((s) => this.generateStatement(s)).join('\n');
      }

      case 'PrintStmt': {
        const args = stmt.expressions.map((e) => this.generateExpression(e)).join(', ');
        return `${this.indent()}কও(${args})`;
      }

      case 'InputStmt': {
        const prompt = stmt.prompt ? `"${stmt.prompt}"` : '""';
        return `${this.indent()}${stmt.identifier} = লও(${prompt})`;
      }

      case 'FunctionDecl': {
        const params = stmt.params.map((p) => p.name).join(', ');
        let res = `${this.indent()}def ${stmt.name}(${params}):\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.body);
        this.indentLevel--;
        return res;
      }

      case 'ReturnStmt': {
        const val = stmt.value ? this.generateExpression(stmt.value) : '';
        return `${this.indent()}return ${val}`.trimEnd();
      }

      case 'BreakStmt':
        return `${this.indent()}break`;

      case 'ContinueStmt':
        return `${this.indent()}continue`;

      case 'ExpressionStmt':
        return `${this.indent()}${this.generateExpression(stmt.expression)}`;
    }
  }

  private generateExpression(expr: ExpressionNode): string {
    switch (expr.type) {
      case 'Literal':
        if (expr.value === true) return 'True';
        if (expr.value === false) return 'False';
        if (expr.value === null) return 'None';
        if (typeof expr.value === 'string') return JSON.stringify(expr.value);
        return String(expr.value);

      case 'Identifier':
        return expr.name;

      case 'BinaryExpr': {
        const left = this.generateExpression(expr.left);
        const right = this.generateExpression(expr.right);
        let op = expr.operator;
        if (op === '&&') op = 'and' as any;
        if (op === '||') op = 'or' as any;
        return `(${left} ${op} ${right})`;
      }

      case 'UnaryExpr': {
        const op = expr.operator === '!' ? 'not ' : expr.operator;
        const operand = this.generateExpression(expr.operand);
        return `(${op}${operand})`;
      }

      case 'FunctionCall': {
        const args = expr.args.map((a) => this.generateExpression(a)).join(', ');
        return `${expr.callee}(${args})`;
      }

      case 'ArrayLiteral': {
        const elements = expr.elements.map((e) => this.generateExpression(e)).join(', ');
        return `[${elements}]`;
      }

      case 'IndexExpr': {
        const arr = this.generateExpression(expr.array);
        const idx = this.generateExpression(expr.index);
        return `${arr}[${idx}]`;
      }
    }
  }
}

// ==========================================
// ANSI C / C99 Code Generator
// ==========================================
export class CGenerator {
  private indentLevel = 0;

  public generate(ast: ProgramNode): string {
    this.indentLevel = 0;
    const functions: string[] = [];
    const mainBody: string[] = [];

    const lines: string[] = [
      '/**',
      ' * Generated by SylhetiLang Compiler Target: C99 / Native',
      ' */',
      '#include <stdio.h>',
      '#include <stdlib.h>',
      '#include <stdbool.h>',
      '#include <string.h>',
      '#include <math.h>',
      '',
    ];

    for (const stmt of ast.body) {
      if (stmt.type === 'FunctionDecl') {
        functions.push(this.generateFunction(stmt));
      } else {
        mainBody.push(this.generateStatement(stmt));
      }
    }

    lines.push(...functions);
    lines.push('');
    lines.push('int main(int argc, char** argv) {');
    this.indentLevel = 1;
    lines.push(...mainBody);
    lines.push('    return 0;');
    this.indentLevel = 0;
    lines.push('}');

    return lines.join('\n');
  }

  private indent(): string {
    return '    '.repeat(this.indentLevel);
  }

  private mapCType(type?: string): string {
    switch (type) {
      case 'int':
        return 'int';
      case 'float':
        return 'double';
      case 'string':
        return 'const char*';
      case 'bool':
        return 'bool';
      case 'void':
        return 'void';
      default:
        return 'int';
    }
  }

  private generateFunction(node: StatementNode & { type: 'FunctionDecl' }): string {
    const retType = this.mapCType(node.returnType);
    const params = node.params.map((p) => `${this.mapCType(p.type)} ${p.name}`).join(', ') || 'void';

    let res = `${retType} ${node.name}(${params}) {\n`;
    this.indentLevel = 1;
    for (const s of node.body.statements) {
      res += this.generateStatement(s) + '\n';
    }
    this.indentLevel = 0;
    res += '}';
    return res;
  }

  private generateStatement(stmt: StatementNode): string {
    switch (stmt.type) {
      case 'VarDecl': {
        const type = this.mapCType(stmt.dataType);
        const init = stmt.init ? ` = ${this.generateExpression(stmt.init)}` : '';
        return `${this.indent()}${type} ${stmt.identifier}${init};`;
      }

      case 'Assignment': {
        const val = this.generateExpression(stmt.value);
        if (stmt.index) {
          const idx = this.generateExpression(stmt.index);
          return `${this.indent()}${stmt.identifier}[${idx}] ${stmt.operator} ${val};`;
        }
        return `${this.indent()}${stmt.identifier} ${stmt.operator} ${val};`;
      }

      case 'IfStmt': {
        const cond = this.generateExpression(stmt.condition);
        let res = `${this.indent()}if (${cond}) {\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.consequent) + '\n';
        this.indentLevel--;
        res += `${this.indent()}}`;

        if (stmt.alternate) {
          res += ` else {\n`;
          this.indentLevel++;
          res += this.generateStatement(stmt.alternate) + '\n';
          this.indentLevel--;
          res += `${this.indent()}}`;
        }
        return res;
      }

      case 'WhileStmt': {
        const cond = this.generateExpression(stmt.condition);
        let res = `${this.indent()}while (${cond}) {\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.body) + '\n';
        this.indentLevel--;
        res += `${this.indent()}}`;
        return res;
      }

      case 'ForStmt': {
        const init = stmt.init ? this.generateStatement(stmt.init).trim().replace(/;$/, '') : '';
        const cond = stmt.condition ? this.generateExpression(stmt.condition) : '1';
        let update = '';
        if (stmt.update) {
          if ('type' in stmt.update && typeof stmt.update.type === 'string') {
            if (stmt.update.type === 'Assignment' || stmt.update.type === 'ExpressionStmt') {
              update = this.generateStatement(stmt.update as StatementNode).trim().replace(/;$/, '');
            } else {
              update = this.generateExpression(stmt.update as ExpressionNode);
            }
          }
        }

        let res = `${this.indent()}for (${init}; ${cond}; ${update}) {\n`;
        this.indentLevel++;
        res += this.generateStatement(stmt.body) + '\n';
        this.indentLevel--;
        res += `${this.indent()}}`;
        return res;
      }

      case 'BlockStmt': {
        return stmt.statements.map((s) => this.generateStatement(s)).join('\n');
      }

      case 'PrintStmt': {
        const formatParts: string[] = [];
        const argParts: string[] = [];

        for (const expr of stmt.expressions) {
          const exprStr = this.generateExpression(expr);
          if (expr.type === 'Literal' && expr.dataType === 'string') {
            formatParts.push('%s');
            argParts.push(exprStr);
          } else if (expr.type === 'Literal' && expr.dataType === 'float') {
            formatParts.push('%f');
            argParts.push(exprStr);
          } else {
            formatParts.push('%d');
            argParts.push(exprStr);
          }
        }

        const fmt = formatParts.join(' ') + '\\n';
        const args = argParts.length > 0 ? ', ' + argParts.join(', ') : '';
        return `${this.indent()}printf("${fmt}"${args});`;
      }

      case 'ReturnStmt': {
        const val = stmt.value ? ` ${this.generateExpression(stmt.value)}` : '';
        return `${this.indent()}return${val};`;
      }

      case 'BreakStmt':
        return `${this.indent()}break;`;

      case 'ContinueStmt':
        return `${this.indent()}continue;`;

      case 'ExpressionStmt':
        return `${this.indent()}${this.generateExpression(stmt.expression)};`;

      default:
        return '';
    }
  }

  private generateExpression(expr: ExpressionNode): string {
    switch (expr.type) {
      case 'Literal':
        if (expr.value === true) return 'true';
        if (expr.value === false) return 'false';
        if (expr.value === null) return 'NULL';
        if (typeof expr.value === 'string') return JSON.stringify(expr.value);
        return String(expr.value);

      case 'Identifier':
        return expr.name;

      case 'BinaryExpr': {
        const left = this.generateExpression(expr.left);
        const right = this.generateExpression(expr.right);
        return `(${left} ${expr.operator} ${right})`;
      }

      case 'UnaryExpr': {
        const operand = this.generateExpression(expr.operand);
        if (expr.isPrefix) {
          return `(${expr.operator}${operand})`;
        }
        return `(${operand}${expr.operator})`;
      }

      case 'FunctionCall': {
        const args = expr.args.map((a) => this.generateExpression(a)).join(', ');
        return `${expr.callee}(${args})`;
      }

      case 'IndexExpr': {
        const arr = this.generateExpression(expr.array);
        const idx = this.generateExpression(expr.index);
        return `${arr}[${idx}]`;
      }

      default:
        return '0';
    }
  }
}
